### ISSUE TITLE
BUG: Super expression must either be null or a function

### ISSUE THREAD

**Issue by josh-fnbtech** [artf/grapesjs#3902]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v95

### Reproducible demo link

can't reproduce on those links

### Describe the bug

trying to import grapesjs in an ember app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by josh-fnbtech** [comment]
trying to import grapesjs in an ember app gives me Super expression must either be null or a function at t.exports (grapes.min.js:2) error.
<img width="1679" alt="Screen Shot 2021-10-29 at 5 22 08 PM" src="https://user-images.githubusercontent.com/44098505/139507599-39c0e2c2-84de-4ff8-8411-72faa10a29c4.png">

**Comment by surendar02997** [comment]
Super expression must either be null or a function 
Error occured in latest grapes js version v0.17.28 while integrating grapesjs with angular application
What is solution for this???

**Comment by artf** [comment]
Are you able to create a reproducible demo on something like Codesandbox?

@surendar02997 is it working with previous versions?

**Comment by surendar02997** [comment]
Yes it is worked on previous version v0.17.27
Once upgraded it shows error , so I downgraded version it worked, but not working in v0.17.28

**Comment by IreAy0** [comment]
Intergrating grapesJs with react application...
Same error in lastest grapesJs versions, and isn't working for older versions too

**Comment by artf** [comment]
I see no issue [here](https://codesandbox.io/s/brave-mcclintock-7ctm7?file=/index.js) with the current version.
Can someone at least provide a bit of code?

**Comment by shelendravashishtha2** [comment]
just by importing grapesjs error is reproduced, while it was working fine in previous versions

import "grapesjs/dist/css/grapes.min.css";
import grapesjs from "grapesjs";

**Comment by Kahore** [comment]
Same for React apps as well with a version ^16.14.0

**Comment by josh-fnbtech** [comment]
any info? still happening.

**Comment by confettidc** [comment]
Hi, same issue happening here, please help fix as soon as possible, thanks.

**Comment by nik736** [comment]
Setup my new MBP and this happens to me as well. +1

**Comment by umid-shahmaliyev** [comment]
Same here...
```
grapes.min.js:2 Uncaught TypeError: Super expression must either be null or a function
    at t.exports (grapes.min.js:2)
    at grapes.min.js:2
    at Module.__webpack_modules__../node_modules/grapesjs/dist/grapes.min.js (grapes.min.js:2)
    at n (grapes.min.js:2)
    at __webpack_modules__../node_modules/grapesjs/dist/grapes.min.js (grapes.min.js:2)
    at grapes.min.js:2
    at grapes.min.js:2
    at Object../node_modules/grapesjs/dist/grapes.min.js (grapes.min.js:2)
    at __webpack_require__ (bootstrap:19)
    at jsonp chunk loading:22
    at package.js:15783
    at package.js:15786
```

**Comment by joungkookismekooki** [comment]
sorry I out. thank you

၂၀၂၁၊ နို ၃၊ ဗုဒ္ဓဟူး ညနေ ၄:၁၅ တွင် Umid Shahmaliyev <
***@***.***> က ရေးခဲ့သည်−

**Comment by artf** [comment]
I published the new 0.17.29 version on npm. Please try it and let me know if it fixes the issue.

**Comment by abozhinov** [comment]
Confirm that only on the LAST version, I have the same error.

**Comment by artf** [comment]
@abozhinov are you talking about the 0.17.28 or 0.17.29?

**Comment by abozhinov** [comment]
0.17.29 is fixed. Thanks for your work man!

**Comment by IreAy0** [comment]
Thanks, the New version works fine.

**Comment by artf** [comment]
Great, thanks for the update.
@josh-fnbtech it was an update in webpack configuration. For some reason, the final build was not playing well if used as a dependency

**Comment by josh-fnbtech** [comment]
good to know! thanks for the fast fix!
